<?php

namespace Database\Seeders;

use App\Models\FleetBrand;
use Illuminate\Database\Seeder;

class FleetBrandSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $fleetBrands = [
            ['id' => 1, 'name' => 'سایر', 'brand_code' => 10000, 'created_at' => null, 'updated_at' => null],
            ['id' => 2, 'name' => 'بنز', 'brand_code' => 1, 'created_at' => null, 'updated_at' => null],
            ['id' => 3, 'name' => 'ولوو', 'brand_code' => 2, 'created_at' => null, 'updated_at' => null],
            ['id' => 4, 'name' => 'ماک', 'brand_code' => 3, 'created_at' => null, 'updated_at' => '2023-08-07 05:54:37'],
            ['id' => 5, 'name' => 'اسکانیا', 'brand_code' => 4, 'created_at' => null, 'updated_at' => '2023-08-07 05:54:37'],
            ['id' => 6, 'name' => 'اینترناش', 'brand_code' => 5, 'created_at' => null, 'updated_at' => '2023-08-07 05:54:37'],
            ['id' => 7, 'name' => 'لیلاند', 'brand_code' => 6, 'created_at' => null, 'updated_at' => '2023-08-07 05:54:37'],
            ['id' => 8, 'name' => 'ایویکو', 'brand_code' => 9, 'created_at' => null, 'updated_at' => '2023-08-07 05:54:37'],
            ['id' => 9, 'name' => 'وایت', 'brand_code' => 10, 'created_at' => null, 'updated_at' => '2023-08-07 05:54:37'],
            ['id' => 10, 'name' => 'تویوتا', 'brand_code' => 13, 'created_at' => null, 'updated_at' => '2023-08-07 05:54:37'],
            ['id' => 11, 'name' => 'داف', 'brand_code' => 14, 'created_at' => null, 'updated_at' => null],
            ['id' => 12, 'name' => 'شورلت', 'brand_code' => 15, 'created_at' => null, 'updated_at' => null],
            ['id' => 13, 'name' => 'فیات', 'brand_code' => 16, 'created_at' => null, 'updated_at' => '2023-08-07 05:54:37'],
            ['id' => 14, 'name' => 'هیوندای', 'brand_code' => 17, 'created_at' => null, 'updated_at' => '2023-08-07 05:54:37'],
            ['id' => 15, 'name' => 'پیکان', 'brand_code' => 18, 'created_at' => null, 'updated_at' => '2023-08-07 05:54:37'],
            ['id' => 16, 'name' => 'رنو', 'brand_code' => 20, 'created_at' => null, 'updated_at' => null],
            ['id' => 17, 'name' => 'مان', 'brand_code' => 21, 'created_at' => null, 'updated_at' => null],
            ['id' => 18, 'name' => 'دوو', 'brand_code' => 22, 'created_at' => null, 'updated_at' => null],
            ['id' => 19, 'name' => 'بادسان', 'brand_code' => 24, 'created_at' => null, 'updated_at' => null],
            ['id' => 20, 'name' => 'آیفا', 'brand_code' => 25, 'created_at' => null, 'updated_at' => '2023-08-07 05:54:37'],
            ['id' => 21, 'name' => 'هینو', 'brand_code' => 26, 'created_at' => null, 'updated_at' => '2023-08-07 05:54:37'],
            ['id' => 22, 'name' => 'جمس', 'brand_code' => 27, 'created_at' => null, 'updated_at' => null],
            ['id' => 23, 'name' => 'ماکروس', 'brand_code' => 28, 'created_at' => null, 'updated_at' => '2023-08-07 05:54:37'],
            ['id' => 24, 'name' => 'نیسان', 'brand_code' => 29, 'created_at' => null, 'updated_at' => '2023-08-07 05:54:37'],
            ['id' => 25, 'name' => 'برلیه', 'brand_code' => 30, 'created_at' => null, 'updated_at' => '2023-08-07 05:54:37'],
            ['id' => 26, 'name' => 'کاماز', 'brand_code' => 31, 'created_at' => null, 'updated_at' => '2023-08-07 05:54:37'],
            ['id' => 27, 'name' => 'بروکوی', 'brand_code' => 32, 'created_at' => null, 'updated_at' => '2023-08-07 05:54:37'],
            ['id' => 28, 'name' => 'پیکاسو', 'brand_code' => 33, 'created_at' => null, 'updated_at' => '2023-08-07 05:54:37'],
            ['id' => 29, 'name' => 'نهنگ', 'brand_code' => 35, 'created_at' => null, 'updated_at' => null],
            ['id' => 30, 'name' => 'اشتایر', 'brand_code' => 36, 'created_at' => null, 'updated_at' => '2023-08-07 05:54:37'],
            ['id' => 31, 'name' => 'میتسو بیشی', 'brand_code' => 38, 'created_at' => null, 'updated_at' => '2023-08-07 05:54:37'],
            ['id' => 32, 'name' => 'کراز', 'brand_code' => 39, 'created_at' => null, 'updated_at' => '2023-08-07 05:54:37'],
            ['id' => 33, 'name' => 'رومان', 'brand_code' => 40, 'created_at' => null, 'updated_at' => null],
            ['id' => 34, 'name' => 'کومر', 'brand_code' => 41, 'created_at' => null, 'updated_at' => '2023-08-07 05:54:37'],
            ['id' => 35, 'name' => 'ماز', 'brand_code' => 42, 'created_at' => null, 'updated_at' => null],
            ['id' => 36, 'name' => 'کروپ', 'brand_code' => 43, 'created_at' => null, 'updated_at' => '2023-08-07 05:54:37'],
            ['id' => 37, 'name' => 'دوج', 'brand_code' => 45, 'created_at' => null, 'updated_at' => null],
            ['id' => 38, 'name' => 'ریو', 'brand_code' => 46, 'created_at' => null, 'updated_at' => '2023-08-07 05:54:37'],
            ['id' => 39, 'name' => 'جی ام سی', 'brand_code' => 47, 'created_at' => null, 'updated_at' => '2023-08-07 05:54:37'],
            ['id' => 40, 'name' => 'فوتون', 'brand_code' => 48, 'created_at' => null, 'updated_at' => null],
            ['id' => 41, 'name' => 'اپیکا', 'brand_code' => 49, 'created_at' => null, 'updated_at' => '2023-08-07 05:54:37'],
            ['id' => 42, 'name' => 'ذیل', 'brand_code' => 50, 'created_at' => null, 'updated_at' => '2023-08-07 05:54:37'],
            ['id' => 43, 'name' => 'فورد', 'brand_code' => 51, 'created_at' => null, 'updated_at' => null],
            ['id' => 44, 'name' => 'گاز', 'brand_code' => 53, 'created_at' => null, 'updated_at' => null],
            ['id' => 45, 'name' => 'آذرخش', 'brand_code' => 55, 'created_at' => null, 'updated_at' => null],
            ['id' => 46, 'name' => 'مزدا', 'brand_code' => 56, 'created_at' => null, 'updated_at' => null],
            ['id' => 47, 'name' => 'ایسوزو', 'brand_code' => 57, 'created_at' => null, 'updated_at' => '2023-08-07 05:54:37'],
            ['id' => 48, 'name' => 'تاتا', 'brand_code' => 58, 'created_at' => null, 'updated_at' => null],
            ['id' => 49, 'name' => 'اتوکار', 'brand_code' => 59, 'created_at' => null, 'updated_at' => '2023-08-07 05:54:37'],
            ['id' => 50, 'name' => 'رهرو', 'brand_code' => 60, 'created_at' => null, 'updated_at' => null],
            ['id' => 51, 'name' => 'ساویم', 'brand_code' => 61, 'created_at' => null, 'updated_at' => '2023-08-07 05:54:37'],
            ['id' => 52, 'name' => 'بلچ', 'brand_code' => 62, 'created_at' => null, 'updated_at' => null],
            ['id' => 53, 'name' => 'اورال', 'brand_code' => 63, 'created_at' => null, 'updated_at' => null],
            ['id' => 54, 'name' => 'سدان', 'brand_code' => 65, 'created_at' => null, 'updated_at' => null],
            ['id' => 55, 'name' => 'فوسو', 'brand_code' => 66, 'created_at' => null, 'updated_at' => null],
            ['id' => 56, 'name' => 'جلز', 'brand_code' => 69, 'created_at' => null, 'updated_at' => null],
            ['id' => 57, 'name' => 'بی ام سی', 'brand_code' => 72, 'created_at' => null, 'updated_at' => '2023-08-07 05:54:37'],
            ['id' => 58, 'name' => 'سنترشن', 'brand_code' => 73, 'created_at' => null, 'updated_at' => null],
            ['id' => 59, 'name' => 'هانوماگ هنشل', 'brand_code' => 75, 'created_at' => null, 'updated_at' => null],
            ['id' => 60, 'name' => 'کانر', 'brand_code' => 76, 'created_at' => null, 'updated_at' => '2023-08-07 05:54:37'],
            ['id' => 61, 'name' => 'ایزو', 'brand_code' => 77, 'created_at' => null, 'updated_at' => '2023-08-07 05:54:37'],
            ['id' => 62, 'name' => 'بدفورد', 'brand_code' => 78, 'created_at' => null, 'updated_at' => null],
            ['id' => 63, 'name' => 'کنتر', 'brand_code' => 79, 'created_at' => null, 'updated_at' => '2023-08-07 05:54:37'],
            ['id' => 64, 'name' => 'برلیت', 'brand_code' => 80, 'created_at' => null, 'updated_at' => '2023-08-07 05:54:37'],
            ['id' => 65, 'name' => 'اشکودا', 'brand_code' => 81, 'created_at' => null, 'updated_at' => null],
            ['id' => 66, 'name' => 'دیاموند', 'brand_code' => 83, 'created_at' => null, 'updated_at' => '2023-08-07 05:54:37'],
            ['id' => 67, 'name' => 'آمیکو', 'brand_code' => 84, 'created_at' => null, 'updated_at' => '2023-08-07 05:54:37'],
            ['id' => 68, 'name' => 'اشکوش', 'brand_code' => 86, 'created_at' => null, 'updated_at' => null],
            ['id' => 69, 'name' => 'زاور', 'brand_code' => 88, 'created_at' => null, 'updated_at' => null],
            ['id' => 70, 'name' => 'هوو', 'brand_code' => 89, 'created_at' => null, 'updated_at' => null],
            ['id' => 71, 'name' => 'کاویان', 'brand_code' => 91, 'created_at' => null, 'updated_at' => '2023-08-07 05:54:37'],
            ['id' => 72, 'name' => 'فاو', 'brand_code' => 92, 'created_at' => null, 'updated_at' => null],
            ['id' => 73, 'name' => 'دانگ فنگ', 'brand_code' => 93, 'created_at' => null, 'updated_at' => null],
            ['id' => 74, 'name' => 'استودبیو', 'brand_code' => 94, 'created_at' => null, 'updated_at' => '2023-08-07 05:54:37'],
            ['id' => 75, 'name' => 'کاتو', 'brand_code' => 95, 'created_at' => null, 'updated_at' => null],
            ['id' => 76, 'name' => 'آستین', 'brand_code' => 96, 'created_at' => null, 'updated_at' => '2023-08-07 05:54:37'],
            ['id' => 77, 'name' => 'ژایر', 'brand_code' => 97, 'created_at' => null, 'updated_at' => '2023-08-07 05:54:37'],
            ['id' => 78, 'name' => 'آسترا', 'brand_code' => 98, 'created_at' => null, 'updated_at' => null],
            ['id' => 79, 'name' => 'هابز', 'brand_code' => 100, 'created_at' => null, 'updated_at' => null],
            ['id' => 80, 'name' => 'تاترا', 'brand_code' => 102, 'created_at' => null, 'updated_at' => null],
            ['id' => 81, 'name' => 'زامیاد', 'brand_code' => 103, 'created_at' => null, 'updated_at' => '2023-08-07 05:54:37'],
            ['id' => 82, 'name' => 'کال بل', 'brand_code' => 104, 'created_at' => null, 'updated_at' => null],
            ['id' => 83, 'name' => 'تی تان', 'brand_code' => 105, 'created_at' => null, 'updated_at' => '2023-08-07 05:54:37'],
            ['id' => 84, 'name' => 'ایران کاوه', 'brand_code' => 106, 'created_at' => null, 'updated_at' => '2023-08-07 05:54:37'],
            ['id' => 85, 'name' => 'ژیلر', 'brand_code' => 108, 'created_at' => null, 'updated_at' => '2023-08-07 05:54:37'],
            ['id' => 86, 'name' => 'GLR200', 'brand_code' => 113, 'created_at' => null, 'updated_at' => null],
            ['id' => 87, 'name' => 'مارال', 'brand_code' => 114, 'created_at' => null, 'updated_at' => null],
            ['id' => 88, 'name' => 'لیبهر', 'brand_code' => 116, 'created_at' => null, 'updated_at' => '2023-08-07 05:54:37'],
            ['id' => 89, 'name' => 'پراگا', 'brand_code' => 117, 'created_at' => null, 'updated_at' => null],
            ['id' => 90, 'name' => 'دای هاتسو', 'brand_code' => 118, 'created_at' => null, 'updated_at' => '2023-08-07 05:54:37'],
            ['id' => 91, 'name' => 'رابامان', 'brand_code' => 119, 'created_at' => null, 'updated_at' => null],
            ['id' => 92, 'name' => 'جک', 'brand_code' => 121, 'created_at' => null, 'updated_at' => null],
            ['id' => 93, 'name' => 'ماموت', 'brand_code' => 122, 'created_at' => null, 'updated_at' => null],
            ['id' => 94, 'name' => 'مایان گوگل', 'brand_code' => 124, 'created_at' => null, 'updated_at' => '2023-08-07 05:54:37'],
            ['id' => 95, 'name' => 'فان', 'brand_code' => 125, 'created_at' => null, 'updated_at' => null],
            ['id' => 96, 'name' => 'یلچ', 'brand_code' => 126, 'created_at' => null, 'updated_at' => '2023-08-07 05:54:37'],
            ['id' => 97, 'name' => 'شاک من', 'brand_code' => 127, 'created_at' => null, 'updated_at' => '2023-08-07 05:54:37'],
            ['id' => 98, 'name' => 'کیا', 'brand_code' => 128, 'created_at' => null, 'updated_at' => '2023-08-07 05:54:37'],
            ['id' => 99, 'name' => 'نورث بنز', 'brand_code' => 129, 'created_at' => null, 'updated_at' => null],
            ['id' => 100, 'name' => 'البرز', 'brand_code' => 130, 'created_at' => null, 'updated_at' => null],
            ['id' => 101, 'name' => 'کنورث', 'brand_code' => 131, 'created_at' => null, 'updated_at' => '2023-08-07 05:54:37'],
            ['id' => 102, 'name' => 'پیکان وانت', 'brand_code' => 136, 'created_at' => null, 'updated_at' => '2023-08-07 05:54:38'],
            ['id' => 103, 'name' => 'داتسون', 'brand_code' => 137, 'created_at' => null, 'updated_at' => null],
            ['id' => 104, 'name' => 'جیپ', 'brand_code' => 138, 'created_at' => null, 'updated_at' => '2023-08-07 05:54:38'],
            ['id' => 105, 'name' => 'لندرور', 'brand_code' => 139, 'created_at' => null, 'updated_at' => null],
            ['id' => 106, 'name' => 'مبارز', 'brand_code' => 141, 'created_at' => null, 'updated_at' => null],
            ['id' => 107, 'name' => 'گرو', 'brand_code' => 143, 'created_at' => null, 'updated_at' => null],
            ['id' => 108, 'name' => 'الوند', 'brand_code' => 145, 'created_at' => null, 'updated_at' => null],
            ['id' => 109, 'name' => 'کادیا', 'brand_code' => 146, 'created_at' => null, 'updated_at' => '2023-08-07 05:54:38'],
            ['id' => 110, 'name' => 'جین بی', 'brand_code' => 149, 'created_at' => null, 'updated_at' => '2023-08-07 05:54:38'],
            ['id' => 111, 'name' => 'لیاز', 'brand_code' => 151, 'created_at' => null, 'updated_at' => '2023-08-07 05:54:38'],
            ['id' => 112, 'name' => 'سهند', 'brand_code' => 152, 'created_at' => null, 'updated_at' => null],
            ['id' => 113, 'name' => 'GMC', 'brand_code' => 1160, 'created_at' => null, 'updated_at' => null],
            ['id' => 114, 'name' => 'دنیز', 'brand_code' => 1200, 'created_at' => null, 'updated_at' => '2023-08-07 05:54:38'],
            ['id' => 115, 'name' => 'بی بن', 'brand_code' => 1220, 'created_at' => null, 'updated_at' => '2023-08-07 05:54:38'],
            ['id' => 116, 'name' => 'اسکاوت', 'brand_code' => 1340, 'created_at' => null, 'updated_at' => '2023-08-07 05:54:38'],
            ['id' => 117, 'name' => 'پسی', 'brand_code' => 1360, 'created_at' => null, 'updated_at' => '2023-08-07 05:54:38'],
            ['id' => 118, 'name' => 'سیماک', 'brand_code' => 1615, 'created_at' => null, 'updated_at' => '2023-08-07 05:54:38'],
            ['id' => 119, 'name' => 'فراز', 'brand_code' => 1616, 'created_at' => null, 'updated_at' => null],
            ['id' => 120, 'name' => 'امپاور', 'brand_code' => 100001, 'created_at' => null, 'updated_at' => null],
            ['id' => 121, 'name' => 'شهاب خودرو', 'brand_code' => 12, 'created_at' => null, 'updated_at' => null],
            ['id' => 122, 'name' => 'پژو', 'brand_code' => 19, 'created_at' => null, 'updated_at' => null],
            ['id' => 123, 'name' => 'سمند', 'brand_code' => 23, 'created_at' => null, 'updated_at' => null],
            ['id' => 124, 'name' => 'رخش', 'brand_code' => 37, 'created_at' => null, 'updated_at' => null],
            ['id' => 125, 'name' => 'ایران خودکفا', 'brand_code' => 52, 'created_at' => null, 'updated_at' => '2023-08-07 05:54:38'],
            ['id' => 126, 'name' => 'کاروان', 'brand_code' => 64, 'created_at' => null, 'updated_at' => '2023-08-07 05:54:38'],
            ['id' => 127, 'name' => 'عقاب', 'brand_code' => 70, 'created_at' => null, 'updated_at' => null],
            ['id' => 128, 'name' => 'سپاهان', 'brand_code' => 71, 'created_at' => null, 'updated_at' => null],
            ['id' => 129, 'name' => 'نئوپلان', 'brand_code' => 74, 'created_at' => null, 'updated_at' => null],
            ['id' => 130, 'name' => 'غزال', 'brand_code' => 82, 'created_at' => null, 'updated_at' => null],
            ['id' => 131, 'name' => 'بیوک', 'brand_code' => 85, 'created_at' => null, 'updated_at' => '2023-08-07 05:54:38'],
            ['id' => 132, 'name' => 'ماگیروس', 'brand_code' => 87, 'created_at' => null, 'updated_at' => '2023-08-07 05:54:38'],
            ['id' => 133, 'name' => 'میتسوبیشی', 'brand_code' => 90, 'created_at' => null, 'updated_at' => '2023-08-07 05:54:38'],
            ['id' => 134, 'name' => 'اروم خودرو', 'brand_code' => 101, 'created_at' => null, 'updated_at' => null],
            ['id' => 135, 'name' => 'پراید', 'brand_code' => 107, 'created_at' => null, 'updated_at' => '2023-08-07 05:54:38'],
            ['id' => 136, 'name' => 'یاتونگ', 'brand_code' => 109, 'created_at' => null, 'updated_at' => '2023-08-07 05:54:38'],
            ['id' => 137, 'name' => 'انگاتی', 'brand_code' => 110, 'created_at' => null, 'updated_at' => '2023-08-07 05:54:38'],
            ['id' => 138, 'name' => 'رهپو', 'brand_code' => 111, 'created_at' => null, 'updated_at' => null],
            ['id' => 139, 'name' => 'پروتون', 'brand_code' => 112, 'created_at' => null, 'updated_at' => null],
            ['id' => 140, 'name' => 'کارسان', 'brand_code' => 115, 'created_at' => null, 'updated_at' => '2023-08-07 05:54:38'],
            ['id' => 141, 'name' => 'فولکس', 'brand_code' => 120, 'created_at' => null, 'updated_at' => '2023-08-07 05:54:38'],
            ['id' => 142, 'name' => 'دلیکا', 'brand_code' => 123, 'created_at' => null, 'updated_at' => '2023-08-07 05:54:38'],
            ['id' => 143, 'name' => 'نارون', 'brand_code' => 132, 'created_at' => null, 'updated_at' => null],
            ['id' => 144, 'name' => 'هوندا', 'brand_code' => 133, 'created_at' => null, 'updated_at' => null],
            ['id' => 145, 'name' => 'سیترا', 'brand_code' => 134, 'created_at' => null, 'updated_at' => '2023-08-07 05:54:38'],
            ['id' => 146, 'name' => 'مهسان', 'brand_code' => 135, 'created_at' => null, 'updated_at' => null],
            ['id' => 147, 'name' => 'ریف', 'brand_code' => 140, 'created_at' => null, 'updated_at' => '2023-08-07 05:54:38'],
            ['id' => 148, 'name' => 'بستا', 'brand_code' => 142, 'created_at' => null, 'updated_at' => null],
            ['id' => 149, 'name' => 'سپهر2', 'brand_code' => 144, 'created_at' => null, 'updated_at' => null],
            ['id' => 150, 'name' => 'پیشرو', 'brand_code' => 148, 'created_at' => null, 'updated_at' => '2023-08-07 05:54:38'],
            ['id' => 151, 'name' => 'دایون', 'brand_code' => 100002, 'created_at' => null, 'updated_at' => '2023-08-07 05:54:38'],
            ['id' => 152, 'name' => 'دیما', 'brand_code' => 100003, 'created_at' => null, 'updated_at' => '2023-08-07 05:54:38'],
            ['id' => 153, 'name' => 'پیلسان', 'brand_code' => 100004, 'created_at' => null, 'updated_at' => '2023-08-07 05:54:38'],
            ['id' => 154, 'name' => 'دافران', 'brand_code' => 100005, 'created_at' => null, 'updated_at' => null],
            ['id' => 155, 'name' => 'سایر', 'brand_code' => 100000, 'created_at' => null, 'updated_at' => '2023-08-07 05:54:38'],
        ];

        FleetBrand::query()->upsert(
            $fleetBrands,
            ['brand_code'],
            ['name', 'created_at', 'updated_at'],
        );
    }
}
