<?php

namespace Database\Seeders;

use App\Models\InsuranceCompany;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class InsuranceCompanySeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
//        DB::table('insurance_companies')->truncate();

        $companies = [
            [
                'id' => 1,
                'name' => 'شرکت بیمه ایران',
                'en_name' => 'Bimeh_Iran',
                'org_code' => 2,
                'economy_code' => null,
                'postal_code' => '1435814715',
                'city_code' => 11320000,
                'state_code' => 11,
                'address' => 'تهران خ برزیل غربی پلاک51',
                'national_code' => '10103858742',
                'phone' => null,
                'website' => null,
            ],
            [
                'id' => 2,
                'name' => 'شرکت بیمه آسیا',
                'en_name' => 'Bimeh_Asia',
                'org_code' => 4,
                'economy_code' => '411111715417',
                'postal_code' => '1598916815',
                'city_code' => 11320000,
                'state_code' => 11,
                'address' => 'خیابان طالقانی بین سپهبد قرنی و استاد نجات الهی شماره 3',
                'national_code' => '10100314757',
                'phone' => '021 - 88800950 - 60',
                'website' => null,
            ],
            [
                'id' => 3,
                'name' => 'شرکت بیمه دانا',
                'en_name' => 'Bimeh_Dana',
                'org_code' => 5,
                'economy_code' => '411111655159',
                'postal_code' => '1517895633',
                'city_code' => 11320000,
                'state_code' => 11,
                'address' => 'استان تهران - شهرستان تهران - بخش مرکزی - شهر تهران-گاندی-خیابان گاندی جنوبی-خیابان پانزدهم-پلاک 2-طبقه نهم-',
                'national_code' => '10100641966',
                'phone' => '88770971-80',
                'website' => null,
            ],
            [
                'id' => 4,
                'name' => 'شرکت بیمه معلم',
                'en_name' => 'Bimeh_Moealem',
                'org_code' => 6,
                'economy_code' => null,
                'postal_code' => '1517973511',
                'city_code' => 11320000,
                'state_code' => 11,
                'address' => 'خیابان حقانی بعد از خیابان گاندی پلاک 5',
                'national_code' => '10101541927',
                'phone' => null,
                'website' => 'https://mic.co.ir',
            ],
            [
                'id' => 5,
                'name' => 'شرکت بیمه البرز',
                'en_name' => 'Bimeh_Alborz',
                'org_code' => 7,
                'economy_code' => '411111461137',
                'postal_code' => '1913777151',
                'city_code' => 11320000,
                'state_code' => 11,
                'address' => 'خیابان دکتر شریعتی بالاتر از خیابان شهید وحید دستگردی ( ظفر سابق ) نبش کوچه آبان پلاک 1',
                'national_code' => '10100314776',
                'phone' => null,
                'website' => 'https://www.ealborzins.ir',
            ],
            [
                'id' => 6,
                'name' => 'شرکت بیمه کارآفرین',
                'en_name' => 'Bimeh_KarAfarin',
                'org_code' => 8,
                'economy_code' => '411111176498',
                'postal_code' => '1513846911',
                'city_code' => 11320000,
                'state_code' => 11,
                'address' => 'استان تهران - شهرستان تهران - بخش مرکزی - شهر تهران-شهید بهشتی-خیابان شهید احمد قصیر-خیابان شهید بهزاد شفق (هفدهم )-پلاک 5-طبقه همکف-',
                'national_code' => '10102425969',
                'phone' => null,
                'website' => null,
            ],
            [
                'id' => 7,
                'name' => 'شرکت بیمه پارسیان',
                'en_name' => 'Bimeh_Parsian',
                'org_code' => 9,
                'economy_code' => '411111593356',
                'postal_code' => '1969633431',
                'city_code' => 11320000,
                'state_code' => 11,
                'address' => 'تهران خیابان ولیعصر بالاتر از بلوار میرداماد خیابان قبادیان پلاک 22',
                'national_code' => '10102424818',
                'phone' => null,
                'website' => null,
            ],
            [
                'id' => 8,
                'name' => 'شرکت بیمه توسعه',
                'en_name' => 'Bimeh_Toseeh',
                'org_code' => 10,
                'economy_code' => '411111474785',
                'postal_code' => '1518818111',
                'city_code' => 11320000,
                'state_code' => 11,
                'address' => 'تهران بزرگراه حقانی چهارراه جهان کودک شماره4',
                'national_code' => '10102425044',
                'phone' => null,
                'website' => null,
            ],
            [
                'id' => 9,
                'name' => 'شرکت بیمه سینا',
                'en_name' => 'Bimeh_Sina',
                'org_code' => 11,
                'economy_code' => '411334164465',
                'postal_code' => '1918973657',
                'city_code' => 11320000,
                'state_code' => 11,
                'address' => 'تهران خیابان میرداماد بین خیابان نفت شمالی و بزرگراه مدرس شماره 225',
                'national_code' => '10102529006',
                'phone' => null,
                'website' => null,
            ],
            [
                'id' => 10,
                'name' => 'شرکت بیمه سامان',
                'en_name' => 'Bimeh_Saman',
                'org_code' => 12,
                'economy_code' => '511115223413',
                'postal_code' => '1513813118',
                'city_code' => 11320000,
                'state_code' => 11,
                'address' => 'تهران خ خالد اسلامبولی ش 113قدیم 123 جدید',
                'national_code' => '10102818130',
                'phone' => '3253',
                'website' => 'https://www.si24.ir',
            ],
            [
                'id' => 11,
                'name' => 'شرکت بیمه رازی',
                'en_name' => 'Bimeh_Rzai',
                'org_code' => 13,
                'economy_code' => null,
                'postal_code' => null,
                'city_code' => 11320000,
                'state_code' => 11,
                'address' => 'خیابان گاندی خیابان سیزدهم پلاک 1',
                'national_code' => '10102425103',
                'phone' => null,
                'website' => null,
            ],
            [
                'id' => 12,
                'name' => 'شرکت بیمه نوین',
                'en_name' => 'Bimeh_Novin',
                'org_code' => 14,
                'economy_code' => '10103808680',
                'postal_code' => '1911933183',
                'city_code' => 11320000,
                'state_code' => 11,
                'address' => 'تهران بلوار میرداماد خ بهروز نبش ک یكم پ1',
                'national_code' => '10103808680',
                'phone' => '2123047',
                'website' => 'https://novininsurance.com',
            ],
            [
                'id' => 13,
                'name' => 'شرکت بیمه دی',
                'en_name' => 'Bimeh_Dey',
                'org_code' => 15,
                'economy_code' => null,
                'postal_code' => '1918955311',
                'city_code' => 11320000,
                'state_code' => 11,
                'address' => 'شهر تهران-میرداماد-خیابان کجور-بلوار میرداماد-پلاک 239-طبقه اول-واحد 1',
                'national_code' => '10102822596',
                'phone' => '021-36242816',
                'website' => null,
            ],
            [
                'id' => 14,
                'name' => 'شرکت بیمه میهن',
                'en_name' => 'Bimeh_Mihan',
                'org_code' => 16,
                'economy_code' => '411337598669',
                'postal_code' => '1511916413',
                'city_code' => 11320000,
                'state_code' => 11,
                'address' => 'تهران -خیابان شهید خالد اسلامبولی، نبش خیابان بیست و هشتم ، پلاک 90',
                'national_code' => '10103698106',
                'phone' => null,
                'website' => null,
            ],
            [
                'id' => 15,
                'name' => 'شرکت بیمه ملت',
                'en_name' => 'Bimeh_Mellat',
                'org_code' => 17,
                'economy_code' => null,
                'postal_code' => '1513814419',
                'city_code' => 11320000,
                'state_code' => 11,
                'address' => 'استان تهران - شهرستان تهران - بخش مرکزی - شهر تهران-شهید بهشتی-خیابان شهید خالد اسلامبولی-خیابان شهید مسعود احمدیان (پانزدهم )-پلاک 14-ساختمان صبا-طبقه چهارم-واحد جنوبی',
                'national_code' => '10102526951',
                'phone' => null,
                'website' => 'melat.ir',
            ],
            [
                'id' => 16,
                'name' => 'شرکت بیمه حافظ',
                'en_name' => 'Bimeh_Hafez',
                'org_code' => 18,
                'economy_code' => '411146477644',
                'postal_code' => '7941776745',
                'city_code' => 11320000,
                'state_code' => 11,
                'address' => 'جزیره کیش ، خیابان سنایی ، بلوار اندیشه ، ساختمان حافظ',
                'national_code' => '10861529526',
                'phone' => null,
                'website' => null,
            ],
            [
                'id' => 17,
                'name' => 'شرکت بیمه اتکایی امین',
                'en_name' => 'Bimeh_Etekayi_Amin',
                'org_code' => 19,
                'economy_code' => null,
                'postal_code' => '1969735413',
                'city_code' => 11320000,
                'state_code' => 11,
                'address' => 'تهران خیابان آفریقا بالاتر از جهان کودک ابتدای والی نژاد برج افرا ط 2 واحد 216',
                'national_code' => '10101605874',
                'phone' => null,
                'website' => null,
            ],
            [
                'id' => 18,
                'name' => 'شرکت بیمه ایران معین',
                'en_name' => 'Bimeh_Iran_Moein',
                'org_code' => 20,
                'economy_code' => null,
                'postal_code' => '1435814775',
                'city_code' => 11320000,
                'state_code' => 11,
                'address' => 'استان تهران، شهرستان تهران، بخش مرکزی، شهر تهران، ونک، خیابان شهید حجت الاسلام عباس شیرازی، خیابان برزیل غربی، پلاک ??، طبقه ?، واحد ??',
                'national_code' => '14011514175',
                'phone' => null,
                'website' => null,
            ],
            [
                'id' => 19,
                'name' => 'شرکت بیمه امید',
                'en_name' => 'Bimeh_Omid',
                'org_code' => 21,
                'economy_code' => '411146476964',
                'postal_code' => '7941773663',
                'city_code' => 64330000,
                'state_code' => 64,
                'address' => 'استان هرمزگان، شهرستان بندرلنگه، بخش کیش، شهر کیش، مجتمع بانکها، بلوار سنایی، بلوار اندیشه، پلاک ?، ان بی او ?، طبقه همکف',
                'national_code' => '10861532066',
                'phone' => null,
                'website' => null,
            ],
            [
                'id' => 20,
                'name' => 'شرکت بیمه پاسارگاد',
                'en_name' => 'Bimeh_Pasargad',
                'org_code' => 23,
                'economy_code' => null,
                'postal_code' => '1414713',
                'city_code' => 11320000,
                'state_code' => 11,
                'address' => 'تهران - فاطمی - خیابان اردشیر - خیابان هشت بهشت - پلاک 2 -طبقه همكف',
                'national_code' => '10103270201',
                'phone' => '021-82486',
                'website' => null,
            ],
            [
                'id' => 21,
                'name' => 'شرکت بیمه اتکایی ایرانیان',
                'en_name' => 'Bimeh_Etekayi_Iranian',
                'org_code' => 25,
                'economy_code' => null,
                'postal_code' => '1945883851',
                'city_code' => 11320000,
                'state_code' => 11,
                'address' => 'استان تهران - منطقه 19 ، شهرستان تهران ، بخش مرکزی ، شهر تهران، محله دروس ، خیابان شهید مرتضی مفاخری ، خیابان شهید یوسف کلاهدوز ، پلاک 10 ، طبقه اول ، واحد شمالی',
                'national_code' => '14009269642',
                'phone' => null,
                'website' => null,
            ],
            [
                'id' => 22,
                'name' => 'شرکت بیمه کوثر',
                'en_name' => 'Bimeh_Kosar',
                'org_code' => 26,
                'economy_code' => '411373871393',
                'postal_code' => '1514937111',
                'city_code' => 11320000,
                'state_code' => 11,
                'address' => 'تهران آرژانتین ابتدای خ الوند',
                'national_code' => '10320357598',
                'phone' => '89382',
                'website' => 'kins.ir',
            ],
            [
                'id' => 23,
                'name' => 'بیمه تعاون',
                'en_name' => 'Bimeh_Teavon',
                'org_code' => 32,
                'economy_code' => '411419317443',
                'postal_code' => '1586843911',
                'city_code' => 11320000,
                'state_code' => 11,
                'address' => 'تهران-شهید بهشتی-خیابان قایم مقام فراهانی-خیابان ششم-پلاک 22-طبقه اول-واحد جنوبd',
                'national_code' => '10320839651',
                'phone' => null,
                'website' => null,
            ],
            [
                'id' => 24,
                'name' => 'بیمه ما',
                'en_name' => 'Bimeh_Ma',
                'org_code' => 33,
                'economy_code' => '411385564833',
                'postal_code' => '1994618317',
                'city_code' => 11320000,
                'state_code' => 11,
                'address' => 'میدان ونک خیابان ونک شماره 9',
                'national_code' => '10320591652',
                'phone' => null,
                'website' => null,
            ],
            [
                'id' => 25,
                'name' => 'بیمه آسماری',
                'en_name' => 'Bimeh_Asmari',
                'org_code' => 34,
                'economy_code' => '411398338711',
                'postal_code' => '7941773416',
                'city_code' => 11320000,
                'state_code' => 11,
                'address' => 'جزیره کیش، خیابان سنایی، مجتمع بانکها، ساختمان امین (پرهام)، بالای بانک گردشگری، طبقه اول، واحد 2',
                'national_code' => '14000218561',
                'phone' => null,
                'website' => null,
            ],
            [
                'id' => 26,
                'name' => 'بیمه سرمد',
                'en_name' => 'Bimeh_Sarmad',
                'org_code' => 35,
                'economy_code' => '411439899949',
                'postal_code' => '1917743153',
                'city_code' => 11320000,
                'state_code' => 11,
                'address' => 'تهران خ نلسون ماندلا پلاک113',
                'national_code' => '10320903570',
                'phone' => null,
                'website' => null,
            ],
            [
                'id' => 27,
                'name' => 'بیمه آرمان',
                'en_name' => 'Bimeh_Arman',
                'org_code' => 36,
                'economy_code' => null,
                'postal_code' => '1549856111',
                'city_code' => 11320000,
                'state_code' => 11,
                'address' => 'بلوار میرداماد خ شمس تبریزی جنوبی پ4',
                'national_code' => '10320718237',
                'phone' => null,
                'website' => null,
            ],
            [
                'id' => 28,
                'name' => 'فاقد بیمه',
                'en_name' => 'Faghed_Bimeh',
                'org_code' => 38,
                'economy_code' => null,
                'postal_code' => null,
                'city_code' => 11320000,
                'state_code' => 11,
                'address' => null,
                'national_code' => null,
                'phone' => null,
                'website' => null,
            ],
            [
                'id' => 29,
                'name' => 'بیمه تجارت نو',
                'en_name' => 'Bimeh_Tejarat_No',
                'org_code' => 39,
                'economy_code' => null,
                'postal_code' => '1544943111',
                'city_code' => 11320000,
                'state_code' => 11,
                'address' => 'استان تهران - منطقه 15 ، شهرستان تهران ، بخش مرکزی ، شهر تهران، محله داوودیه ، کوچه کتابی ، خیابان شهید حسین دیباج ، پلاک 4 ، طبقه اول',
                'national_code' => '14005725237',
                'phone' => null,
                'website' => null,
            ],
            [
                'id' => 30,
                'name' => 'بیمه متقابل اطمینان متحد قشم',
                'en_name' => 'Bimeh_Motaghabel_Etminan_Motahed_Gheshm',
                'org_code' => 40,
                'economy_code' => null,
                'postal_code' => null,
                'city_code' => 11320000,
                'state_code' => 11,
                'address' => null,
                'national_code' => null,
                'phone' => null,
                'website' => null,
            ],
            [
                'id' => 31,
                'name' => 'بیمه متقابل کیش',
                'en_name' => 'Bimeh_Motaghabel_Kish',
                'org_code' => 41,
                'economy_code' => null,
                'postal_code' => null,
                'city_code' => 11320000,
                'state_code' => 11,
                'address' => null,
                'national_code' => null,
                'phone' => null,
                'website' => null,
            ],
            [
                'id' => 32,
                'name' => 'دانا) شرکت های ادغامی(',
                'en_name' => 'Sherkathaye_Edghami_Dana',
                'org_code' => 42,
                'economy_code' => null,
                'postal_code' => '1571754911',
                'city_code' => 11320000,
                'state_code' => 11,
                'address' => 'استان تهران ، شهرستان تهران ، بخش مرکزی ، شهر تهران، محله امجدیه-خاقانی ، خیابان ملک الشعراء بهار ، خیابان ورزنده ، پلاک 8 ، طبقه همکف ، واحد 1',
                'national_code' => '14010230653',
                'phone' => null,
                'website' => null,
            ],
            [
                'id' => 33,
                'name' => 'اتکایی بیمه مرکزی ج.ا.ا',
                'en_name' => 'Etekayi_Bimeh_Markazi_IRR',
                'org_code' => 43,
                'economy_code' => null,
                'postal_code' => '1435814715',
                'city_code' => 11320000,
                'state_code' => 11,
                'address' => 'استان تهران، شهرستان تهران، بخش مرکزی، شهر تهران، ونك، خیابان شهید حجت الاسلام عباس شیرازی، خیابان برزیل غربی، پلاک 51 ،-ساختمان بیمه ایران، طبقه 1',
                'national_code' => '10103858742 ',
                'phone' => null,
                'website' => 'www.centinsur.ir',
            ],
            [
                'id' => 34,
                'name' => 'حساب اتکایی ویژه',
                'en_name' => 'Hesab_Etekayi_Vijeh',
                'org_code' => 44,
                'economy_code' => null,
                'postal_code' => null,
                'city_code' => 11320000,
                'state_code' => 11,
                'address' => null,
                'national_code' => null,
                'phone' => null,
                'website' => null,
            ],
            [
                'id' => 35,
                'name' => 'بیمه حکمت صبا',
                'en_name' => 'Bimeh_Hekmat_Saba',
                'org_code' => 45,
                'economy_code' => '411531671997',
                'postal_code' => '1514935663',
                'city_code' => 11320000,
                'state_code' => 11,
                'address' => 'تهران-شهر تهران-آرژانتین-خیابان زاگرس-خیابان شهیده راشل کوری(بیست و هفتم )-پلاک 6-طبقه اول',
                'national_code' => '14006513174',
                'phone' => null,
                'website' => null,
            ],
            [
                'id' => 36,
                'name' => 'بیمه زندگی خاورمیانه',
                'en_name' => 'Bimeh_Zendagi_Khavarmiyaneh',
                'org_code' => 46,
                'economy_code' => null,
                'postal_code' => null,
                'city_code' => 11320000,
                'state_code' => 11,
                'address' => null,
                'national_code' => null,
                'phone' => null,
                'website' => null,
            ],
            [
                'id' => 37,
                'name' => 'بیمه زندگی باران',
                'en_name' => 'Bimeh_Zendagi_Baran',
                'org_code' => 47,
                'economy_code' => null,
                'postal_code' => null,
                'city_code' => 11320000,
                'state_code' => 11,
                'address' => null,
                'national_code' => null,
                'phone' => null,
                'website' => null,
            ]
        ];

        foreach ($companies as $company) {
            InsuranceCompany::create($company);
        }
    }
}
