<?php

use App\Enums\FleetOwnershipType;
use App\Enums\StatusEnum;
use App\Enums\UserStatusEnum;

return [
    'waybills' => [
        ['name' => 'sender_id', 'type' => 'unsignedBigInteger', 'index' => true],
        ['name' => 'sender_national_identifier', 'type' => 'string', 'length' => 20],
        ['name' => 'sender_first_name', 'type' => 'string'],
        ['name' => 'sender_last_name', 'type' => 'string'],
        ['name' => 'sender_mobile', 'type' => 'string', 'length' => 20],
        ['name' => 'receiver_id', 'type' => 'unsignedBigInteger', 'index' => true],
        ['name' => 'receiver_national_identifier', 'type' => 'string', 'length' => 20],
        ['name' => 'receiver_first_name', 'type' => 'string'],
        ['name' => 'receiver_last_name', 'type' => 'string'],
        ['name' => 'receiver_mobile', 'type' => 'string', 'length' => 20],
        ['name' => 'driver1_id', 'type' => 'unsignedBigInteger', 'index' => true],
        ['name' => 'driver1_national_code', 'type' => 'string'],
        ['name' => 'driver1_first_name', 'type' => 'string'],
        ['name' => 'driver1_last_name', 'type' => 'string'],
        ['name' => 'driver1_phone', 'type' => 'string', 'length' => 20],
        ['name' => 'driver2_id', 'type' => 'unsignedBigInteger', 'index' => true],
        ['name' => 'driver2_national_code', 'type' => 'string'],
        ['name' => 'driver2_first_name', 'type' => 'string'],
        ['name' => 'driver2_last_name', 'type' => 'string'],
        ['name' => 'driver2_phone', 'type' => 'string', 'length' => 20],
        ['name' => 'referral_driver_id', 'type' => 'unsignedBigInteger', 'index' => true],
        ['name' => 'referral_driver_national_code', 'type' => 'string'],
        ['name' => 'referral_driver_first_name', 'type' => 'string'],
        ['name' => 'referral_driver_last_name', 'type' => 'string'],
        ['name' => 'referral_driver_phone', 'type' => 'string', 'length' => 20],
        ['name' => 'fleet_id', 'type' => 'unsignedBigInteger', 'index' => true],
        ['name' => 'referral_weight', 'type' => 'decimal', 'total' => 15, 'places' => 3],
        ['name' => 'quantity', 'type' => 'unsignedInteger'],
        ['name' => 'loading_started_at', 'type' => 'dateTime'],
        ['name' => 'loading_ended_at', 'type' => 'dateTime'],
        ['name' => 'referral_number', 'type' => 'string'],
        ['name' => 'bijak_number', 'type' => 'string'],
        ['name' => 'serial_number', 'type' => 'string'],
        ['name' => 'issued_at', 'type' => 'dateTime'],
        ['name' => 'liability_insurance', 'type' => 'string'],
        ['name' => 'bijak_tracking_code', 'type' => 'string', 'length' => 8, 'unique' => true],
        ['name' => 'description', 'type' => 'text'],
        ['name' => 'is_incomplete', 'type' => 'boolean', 'default' => true, 'nullable' => false],
        ['name' => 'transport_contract_id', 'type' => 'unsignedBigInteger', 'index' => true, 'foreign' => ['table' => 'transport_contracts', 'column' => 'id']],
        ['name' => 'base_freight_amount', 'type' => 'unsignedBigInteger'],
        ['name' => 'advance_freight_amount', 'type' => 'unsignedBigInteger'],
        ['name' => 'weighbridge_amount', 'type' => 'unsignedBigInteger'],
        ['name' => 'loading_amount', 'type' => 'unsignedBigInteger'],
        ['name' => 'warehousing_amount', 'type' => 'unsignedBigInteger'],
        ['name' => 'commission_amount', 'type' => 'unsignedBigInteger'],
        ['name' => 'insurance_amount', 'type' => 'unsignedBigInteger'],
        ['name' => 'insurance_tax_amount', 'type' => 'unsignedBigInteger'],
        ['name' => 'detention_amount', 'type' => 'unsignedBigInteger'],
        ['name' => 'driver_receivable_amount', 'type' => 'unsignedBigInteger'],
        ['name' => 'payable_amount', 'type' => 'unsignedBigInteger'],
        ['name' => 'freight_at_origin', 'type' => 'boolean', 'default' => false, 'nullable' => false],
        ['name' => 'is_fixed', 'type' => 'boolean', 'default' => false, 'nullable' => false],
    ],
    'waybill_cargos' => [
        ['name' => 'waybill_id', 'type' => 'unsignedBigInteger', 'nullable' => false, 'index' => true, 'foreign' => ['company_table' => 'waybills', 'column' => 'id', 'on_delete' => 'cascade']],
        ['name' => 'cargo_id', 'type' => 'unsignedBigInteger', 'nullable' => false, 'index' => true, 'foreign' => ['table' => 'cargos', 'column' => 'id']],
        ['name' => 'packaging_id', 'type' => 'unsignedBigInteger', 'nullable' => false, 'index' => true, 'foreign' => ['table' => 'packagings', 'column' => 'id']],
        ['name' => 'title', 'type' => 'string', 'nullable' => false],
        ['name' => 'origin_weight', 'type' => 'decimal', 'total' => 15, 'places' => 3, 'nullable' => false],
        ['name' => 'value', 'type' => 'unsignedBigInteger', 'nullable' => false],
        ['name' => 'quantity', 'type' => 'unsignedInteger', 'nullable' => false],
        ['name' => 'is_traffic', 'type' => 'boolean', 'default' => false, 'nullable' => false],
        ['name' => 'is_returned', 'type' => 'boolean', 'default' => false, 'nullable' => false],
        ['name' => 'cottage_number', 'type' => 'string'],
        ['name' => 'cottage_number_2', 'type' => 'string'],
        ['name' => 'driver_account_number', 'type' => 'string'],
        ['name' => 'container_number', 'type' => 'string'],
        ['name' => 'container_number_2', 'type' => 'string'],
    ],
    'drivers' => [
        ['name' => 'national_code', 'type' => 'string', 'nullable' => false],
        ['name' => 'first_name', 'type' => 'string', 'nullable' => false],
        ['name' => 'last_name', 'type' => 'string', 'nullable' => false],
        ['name' => 'full_name', 'type' => 'string', 'nullable' => false],
        ['name' => 'father_name', 'type' => 'string', 'nullable' => false],
        ['name' => 'license_number', 'type' => 'string', 'nullable' => false],
        [
            'name' => 'license_type',
            'type' => 'unsignedBigInteger',
            'nullable' => false,
            'index' => true,
            'foreign' => ['table' => 'driver_license_types', 'column' => 'id'],
        ],
        ['name' => 'license_expiry_date', 'type' => 'date', 'nullable' => false],
        ['name' => 'phone_number_1', 'type' => 'string'],
        ['name' => 'phone_number_2', 'type' => 'string'],
        ['name' => 'phone_number_3', 'type' => 'string'],
        ['name' => 'profile_image_path', 'type' => 'string'],
        ['name' => 'description', 'type' => 'text'],
        [
            'name' => 'status',
            'type' => 'enum',
            'values' => UserStatusEnum::values(),
            'default' => UserStatusEnum::ACTIVE->value,
            'nullable' => false,
        ],
    ],
    'shipment_parties' => [
        ['name' => 'national_identifier', 'type' => 'string', 'length' => 20, 'nullable' => false, 'unique' => true],
        ['name' => 'is_sender', 'type' => 'boolean', 'default' => false, 'nullable' => false],
        ['name' => 'is_receiver', 'type' => 'boolean', 'default' => false, 'nullable' => false],
        [
            'name' => 'status',
            'type' => 'enum',
            'values' => StatusEnum::values(),
            'default' => StatusEnum::ACTIVE->value,
            'nullable' => false,
        ],
        ['name' => 'title', 'type' => 'string'],
        ['name' => 'first_name', 'type' => 'string'],
        ['name' => 'last_name', 'type' => 'string'],
        ['name' => 'mobile', 'type' => 'string', 'length' => 20],
        ['name' => 'landline', 'type' => 'string', 'length' => 20],
        ['name' => 'intermediary_code', 'type' => 'string', 'index' => true],
        ['name' => 'transportation_code', 'type' => 'string', 'index' => true],
        ['name' => 'email', 'type' => 'string'],
        ['name' => 'description', 'type' => 'text'],
    ],
    'shipment_party_addresses' => [
        [
            'name' => 'shipment_party_id',
            'type' => 'unsignedBigInteger',
            'nullable' => false,
            'index' => true,
            'foreign' => [
                'company_table' => 'shipment_parties',
                'column' => 'id',
                'on_delete' => 'cascade',
            ],
        ],
        ['name' => 'postal_code', 'type' => 'string', 'length' => 20, 'nullable' => false],
        ['name' => 'phone', 'type' => 'string', 'length' => 11, 'nullable' => true],
        [
            'name' => 'city_code',
            'type' => 'unsignedInteger',
            'nullable' => false,
            'index' => true,
            'foreign' => ['table' => 'cities', 'column' => 'code'],
        ],
        ['name' => 'address', 'type' => 'text', 'nullable' => false],
        ['name' => 'description', 'type' => 'text'],
    ],
    'fleets' => [
        ['name' => 'smart_card_number', 'type' => 'string', 'nullable' => true, 'unique' => true, 'change' => true],
        [
            'name' => 'status',
            'type' => 'enum',
            'values' => StatusEnum::values(),
            'default' => StatusEnum::ACTIVE->value,
            'nullable' => false,
        ],
        [
            'name' => 'ownership_type',
            'type' => 'enum',
            'values' => FleetOwnershipType::values(),
            'default' => FleetOwnershipType::Unknown->value,
            'nullable' => false,
        ],
        ['name' => 'plate_first_number', 'type' => 'string', 'length' => 2, 'nullable' => false],
        ['name' => 'plate_second_letter', 'type' => 'string', 'length' => 1, 'nullable' => false],
        ['name' => 'plate_third_number', 'type' => 'string', 'length' => 3, 'nullable' => false],
        ['name' => 'plate_fourth_number', 'type' => 'string', 'length' => 2, 'nullable' => false],
        ['name' => 'manufacture_year', 'type' => 'unsignedSmallInteger', 'nullable' => true, 'change' => true],
        [
            'name' => 'driver_license_type_id',
            'type' => 'unsignedBigInteger',
            'nullable' => true,
            'change' => true,
            'index' => true,
            'foreign' => ['table' => 'driver_license_types', 'column' => 'id'],
        ],
        ['name' => 'owner_mobile', 'type' => 'string', 'length' => 20, 'nullable' => true, 'change' => true],
        [
            'name' => 'loading_type_id',
            'type' => 'unsignedBigInteger',
            'nullable' => true,
            'change' => true,
            'index' => true,
            'foreign' => ['table' => 'loading_types', 'column' => 'id'],
        ],
        ['name' => 'insurance_policy_number', 'type' => 'string', 'nullable' => true, 'change' => true],
        ['name' => 'chassis_number', 'type' => 'string', 'nullable' => true, 'change' => true],
        ['name' => 'engine_number', 'type' => 'string', 'nullable' => true, 'change' => true],
        ['name' => 'vin', 'type' => 'string', 'length' => 50, 'nullable' => true, 'change' => true],
        [
            'name' => 'system_id',
            'type' => 'unsignedBigInteger',
            'nullable' => true,
            'change' => true,
            'index' => true,
            'foreign' => ['table' => 'fleet_brands', 'column' => 'id'],
        ],
        [
            'name' => 'tip_code',
            'type' => 'unsignedBigInteger',
            'nullable' => true,
            'change' => true,
            'index' => true,
            'foreign' => ['table' => 'fleet_types', 'column' => 'tip_code'],
        ],
        ['name' => 'document_date', 'type' => 'date', 'nullable' => true, 'change' => true],
        ['name' => 'document_number', 'type' => 'string', 'nullable' => true, 'change' => true],
        ['name' => 'insurance_date', 'type' => 'date', 'nullable' => true, 'change' => true],
        ['name' => 'technical_inspection_valid_until', 'type' => 'date', 'nullable' => true, 'change' => true],
        ['name' => 'has_violation', 'type' => 'boolean', 'default' => false, 'nullable' => false],
        ['name' => 'description', 'type' => 'text'],
    ],
    'cargos' => [
        ['name' => 'name', 'type' => 'string'],
        ['name' => 'national_code', 'type' => 'string'],
    ],
    'product_owner' => [
        ['name' => 'name', 'type' => 'string'],
        ['name' => 'phone', 'type' => 'string', 'length' => 20],
        ['name' => 'transportation_code', 'type' => 'string'],
    ],
];
